# 50

In [1]:
# 런타임 1분 30초 소요
!pip install transformers
from transformers import BartTokenizer, TFBartForConditionalGeneration

# 모델 및 토크나이저 불러오기
model = TFBartForConditionalGeneration.from_pretrained('facebook/bart-large')
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:99: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/1.63k [00:00<?, ?B/s]

tf_model.h5:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBartForConditionalGeneration.

All the layers of TFBartForConditionalGeneration were initialized from the model checkpoint at facebook/bart-large.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

### Bart(Denoising Sequence-to-Sequence Pre-training for Natural Language Generation, Translation, and Comprehension)(2020))

[영어](https://arxiv.org/abs/1910.13461)  
[한글1](https://velog.io/@dutch-tulip/BART)  
[한글2](https://dladustn95.github.io/nlp/BART_paper_review/)



# BART

## 목적

BART(Bidirectional and Auto-Regressive Transformers) 모델은 다양한 자연어 처리(NLP) 작업에서 높은 성능을 발휘하기 위해 설계된 **텍스트 생성 모델**. BART는 텍스트의 **복원 및 생성** 작업에 주로 사용되며, 그 목적은 다음과 같다:

- **텍스트 요약**: 긴 문서의 핵심 내용을 간결하게 요약.
- **기계 번역**: 한 언어의 텍스트를 다른 언어로 변환.
- **텍스트 복원**: 손상된 텍스트를 원래의 형태로 복원.
- **질문 생성**: 주어진 텍스트를 바탕으로 질문을 생성.

BART의 목표는 입력된 텍스트를 인코딩하여 중요한 정보를 추출하고, 이를 바탕으로 원하는 형태의 텍스트를 생성하는 것이다.

## 아키텍처

BART는 **Transformer 인코더-디코더 아키텍처**를 기반으로 한다. 이 아키텍처는 다음과 같은 특징을 갖는다:

- **인코더(Encoder)**: 입력 텍스트를 받아 고정된 크기의 잠재 표현(latent representation)으로 인코딩한다. BERT와 유사하게 양방향(Bidirectional)으로 텍스트를 처리하여 입력 시퀀스의 문맥을 학습.
  
- **디코더(Decoder)**: 인코더에서 생성된 잠재 표현을 받아 출력 시퀀스를 생성. GPT와 유사하게 순차적으로 텍스트를 생성하는 자동 회귀(Auto-Regressive) 방식을 사용.

![](https://dladustn95.github.io/assets/images/bart_figure1.png)

BART는 다음과 같은 방식으로 텍스트를 처리:

![](https://dladustn95.github.io/assets/images/bart_figure2.png)

1. **손상된 텍스트 입력**: 원래 텍스트를 마스킹, 순서 뒤바꿈, 삭제 등의 방법으로 손상시킨 후 입력으로 사용.
2. **인코딩**: 손상된 텍스트를 인코더에 입력하여 중요한 정보를 추출.
3. **디코딩**: 추출된 정보를 바탕으로 디코더에서 원래 텍스트를 복원하거나 새로운 텍스트를 생성.

## 실험

BART는 다양한 NLP 과제에서 실험적으로 검증됨. 주요 실험으로는 다음과 같다:

- **텍스트 요약**: CNN/DailyMail 데이터셋을 사용하여 뉴스 기사의 요약문을 생성하는 실험을 수행. BART는 긴 문서를 인코딩하여 중요한 정보를 추출한 후, 간결한 요약문을 생성.

- **기계 번역**: WMT 데이터셋을 사용하여 영어-독일어 번역 작업을 수행. BART는 양방향 인코딩과 자동 회귀 디코딩을 결합하여 높은 품질의 번역문을 생성.

- **텍스트 복원**: 손상된 텍스트를 원래 형태로 복원하는 실험을 통해 BART의 텍스트 복원 능력을 평가.

각 실험은 BART의 다양한 텍스트 생성 및 복원 작업에서의 성능을 평가하는 데 사용됨.

![Sequence Classification TasksPermalink](https://dladustn95.github.io/assets/images/bart_figure3.png)

![Machine Translation](https://dladustn95.github.io/assets/images/bart_figure4.png)

## 성능

BART는 여러 NLP 작업에서 최첨단 성능을 기록하며, 다음과 같은 장점을 보여줌:

- **텍스트 요약**: BART는 ROUGE 점수에서 다른 최신 모델들보다 높은 성능을 보여주며, 긴 문서를 효율적으로 요약할 수 있음을 입증.
- **기계 번역**: BART는 BLEU 점수에서 탁월한 성능을 보였으며, 다양한 언어 쌍에서 높은 품질의 번역문을 생성.
- **텍스트 복원**: 손상된 텍스트를 원래 형태로 정확하게 복원하는 능력이 뛰어남.

![](https://dladustn95.github.io/assets/images/bart_figure7.png)

## 결론

BART는 인코더-디코더 아키텍처를 기반으로 한 강력한 텍스트 생성 모델로, 텍스트 요약, 기계 번역, 텍스트 복원 등 다양한 NLP 작업에서 우수한 성능을 발휘. BART의 양방향 인코딩과 자동 회귀 디코딩 전략은 텍스트의 문맥을 정확하게 이해하고, 자연스러운 텍스트를 생성하는 데 중요한 역할을 함.



In [8]:
model

In [9]:
model.summary()

Model: "tf_bart_for_conditional_generation"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 model (TFBartMainLayer)     multiple                  406291456 
                                                                 
 final_logits_bias (BiasLay  multiple                  50265     
 er)                                                             
                                                                 
Total params: 406341721 (1.51 GB)
Trainable params: 406291456 (1.51 GB)
Non-trainable params: 50265 (196.35 KB)
_________________________________________________________________


In [10]:
for layer in model.layers:
    print(layer)

In [11]:
from transformers import BartConfig

config = model.config
print(config)

BartConfig {
  "_name_or_path": "facebook/bart-large",
  "activation_dropout": 0.1,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartModel"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": 0,
  "classif_dropout": 0.1,
  "classifier_dropout": 0.0,
  "d_model": 1024,
  "decoder_attention_heads": 16,
  "decoder_ffn_dim": 4096,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 12,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "early_stopping": true,
  "encoder_attention_heads": 16,
  "encoder_ffn_dim": 4096,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 12,
  "eos_token_id": 2,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_position_embeddings": 1024,
  "mode

In [12]:
# 인코더 레이어 확인
for layer in model.get_encoder().layers:
    print(layer)

# 디코더 레이어 확인
for layer in model.get_decoder().layers:
    print(layer)

In [15]:
article = "The quick brown fox jumps over the lazy dog."
inputs = tokenizer(article, max_length=1024, return_tensors='tf', truncation=True)

outputs = model(inputs['input_ids'])

print(f"Input shape: {inputs['input_ids'].shape}")
print(f"Output shape: {outputs.logits.shape}")

Input shape: (1, 12)
Output shape: (1, 12, 50265)


In [16]:
# 최대 시퀀스 길이 확인
print(f"Tokenizer max length: {tokenizer.model_max_length}")

Tokenizer max length: 1024


# 51

In [2]:
import re

article = """
Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company in the world"[10] and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence.[11][12][13] Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.

Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's Internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.[14]

The company has since rapidly grown to offer a multitude of products and services beyond Google Search, many of which hold dominant market positions. These products address a wide range of use cases, including email (Gmail), navigation (Waze & Maps), cloud computing (Cloud), web browsing (Chrome), video sharing (YouTube), productivity (Workspace), operating systems (Android), cloud storage (Drive), language translation (Translate), photo storage (Photos), video calling (Meet), smart home (Nest), smartphones (Pixel), wearable technology (Pixel Watch & Fitbit), music streaming (YouTube Music), video on demand (YouTube TV), artificial intelligence (Google Assistant), machine learning APIs (TensorFlow), AI chips (TPU), and more. Discontinued Google products include gaming (Stadia), Glass,[citation needed] Google+, Reader, Play Music, Nexus, Hangouts, and Inbox by Gmail.[15][16]

Google's other ventures outside of Internet services and consumer electronics include quantum computing (Sycamore), self-driving cars (Waymo, formerly the Google Self-Driving Car Project), smart cities (Sidewalk Labs), and transformer models (Google Brain).[17]

Google and YouTube are the two most visited websites worldwide followed by Facebook and Twitter. Google is also the largest search engine, mapping and navigation application, email provider, office suite, video sharing platform, photo and cloud storage provider, mobile operating system, web browser, ML framework, and AI virtual assistant provider in the world as measured by market share. On the list of most valuable brands, Google is ranked second by Forbes[18] and fourth by Interbrand.[19] It has received significant criticism involving issues such as privacy concerns, tax avoidance, censorship, search neutrality, antitrust and abuse of its monopoly position.
"""

print("before:")
print(article)

# 정규식 적용
article = re.sub(r"[:.]\[[0-9]+\](.*?)\([0-9]+\)|.?[([][0-9]+[])]|\n|\r", r"", article)

print("after:")
print(article)

before:

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company in the world"[10] and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence.[11][12][13] Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.

Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google 

# 52

In [3]:
# 토크나이저로 인코딩
inputs = tokenizer([article], max_length=1024, return_tensors='tf', truncation=True)
inputs

{'input_ids': <tf.Tensor: shape=(1, 609), dtype=int32, numpy=
array([[    0, 20441,  2291,    16,    41,   470, 17043,   806,   138,
         5650,    15,  1707,  3819,   806,     6,   804,  4579,     6,
         3613, 11730,     6,  3034,  2257,     6, 17997, 11730,     6,
          364,    12,  8342,     6,  7350,  2316,     8,  2267,  8917,
            4,    85,    34,    57,  4997,     7,    25,    22,   627,
          144,  2247,   138,    11,     5,   232,     8,    65,     9,
            5,   232,    18,   144,  5130,  3595,   528,     7,    63,
          210, 12532,     6,   414,  2783,     6,     8,  9874, 12340,
           11,     5,   443,     9,  7350,  2316,  3139,  4095,   138,
        15023,    16,  1687,    65,     9,     5,  1776,  4934,   470,
          335,   806,   451,     6,  2863,  1645,     6,  1257,     6,
        37622,     6,     8,  3709,     4, 20441,    21,  4790,    15,
          772,   204,     6,  6708,     6,    30,  6045,  7086,     8,
        23509, 

# 53

In [4]:
# 텐서플로우 타입인 inputs['input_ids]를 넘파이 어레이 타입으로 변경
inputs['input_ids'].numpy()

array([[    0, 20441,  2291,    16,    41,   470, 17043,   806,   138,
         5650,    15,  1707,  3819,   806,     6,   804,  4579,     6,
         3613, 11730,     6,  3034,  2257,     6, 17997, 11730,     6,
          364,    12,  8342,     6,  7350,  2316,     8,  2267,  8917,
            4,    85,    34,    57,  4997,     7,    25,    22,   627,
          144,  2247,   138,    11,     5,   232,     8,    65,     9,
            5,   232,    18,   144,  5130,  3595,   528,     7,    63,
          210, 12532,     6,   414,  2783,     6,     8,  9874, 12340,
           11,     5,   443,     9,  7350,  2316,  3139,  4095,   138,
        15023,    16,  1687,    65,     9,     5,  1776,  4934,   470,
          335,   806,   451,     6,  2863,  1645,     6,  1257,     6,
        37622,     6,     8,  3709,     4, 20441,    21,  4790,    15,
          772,   204,     6,  6708,     6,    30,  6045,  7086,     8,
        23509,  2265,   179,   150,    51,    58, 15221,   521,    23,
      

# 54

In [5]:
# 런타임 30초 소요
# 문장 요약 생성 결과(vocabulary ID)를 summary_ids에 저장
summary_ids = model.generate(inputs['input_ids'], num_beams=5, max_length=25)
summary_ids

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[    2,     0, 20441,  2291,    16,    41,   470, 17043,   806,
          138,  5650,    15,  1707,  3819,   806,     6,   804,  4579,
            6,  3613, 11730,     6,  3034,  2257,     2]], dtype=int32)>

# 55

In [6]:
# summary_ids 디코딩
print(''.join([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids]))

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software


In [7]:
inputs = tokenizer([article], max_length=1024, return_tensors='tf', truncation=True)
summary_ids = model.generate(inputs['input_ids'], num_beams=5, max_length=25)
print(''.join([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids]))

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software
